### ISSUE TITLE
The state of the go packages

### ISSUE THREAD

**Issue by illiliti** [kiss-community/community#976]
Some(well, all of them except dnscrypt-proxy) go packages still use internet connection to fetch dependencies. This is bad because only kiss itself should be allowed(we should really enforce this via unshare) to fetch something from internet. We should use `go build -mod=vendor` where possible, and if not possible - convince upstream to add support for it. 

* [ ] syncthing -- @Vouivre switch to this [source](https://github.com/syncthing/syncthing/releases/download/v1.19.0/syncthing-source-v1.19.0.tar.gz) and use `go build -mod=vendor`
* [ ] age -- waiting for upstream decision https://github.com/FiloSottile/age/discussions/394
* [ ] caddy -- waiting for upstream decision https://github.com/caddyserver/caddy/issues/4573
* [ ] micro -- waiting for upstream decision https://github.com/zyedidia/micro/issues/2364
* [ ] fzf -- waiting for upstream decision https://github.com/junegunn/fzf/issues/2733
* [ ] amfora -- waiting for upstream decision https://github.com/makeworld-the-better-one/amfora/issues/296
* [ ] github-cli -- waiting for upstream decision https://github.com/cli/cli/issues/5201
* [ ] go-ipfs -- @Vouivre set `GOFLAGS='-mod=vendor'`
* [ ] aerc-git -- TBD
* [ ] gron-git -- upstream is kinda dead
* [ ] rclone -- @xuxiaodong upstream provides extra [tarball](https://github.com/rclone/rclone/releases/download/v1.57.0/rclone-v1.57.0-vendor.tar.gz) with vendored dependencies
* [ ] restric -- waiting for upstream decision https://github.com/restic/restic/issues/3647
* [ ] slides -- waiting for upstream decision https://github.com/maaslalani/slides/issues/137
* [ ] (gi)tea -- @mmatongo set `GOFLAGS='-mod=vendor'`
* [x] goimports -- ~~FUCK YOU GOOGLE!~~

**Comment by Mohm730** [comment]
> https://www.facebook.com/profile.php?id=100024552463286

**Comment by Vouivre** [comment]
I'm not the maintainer of `go-ipfs`

```
$ kiss-maintainer go-ipfs                                                      
=> /home/user/repos/community/community/go-ipfs
Daniel M. Matongo <me@danielm.pw>
```

@mmatongo: can you have a look at it ?

**Comment by mmatongo** [comment]
I keep forgetting to do this for some reason, I'll send two PR's in a bit.

**Comment by illiliti** [comment]
> I'm not the maintainer of `go-ipfs`

Fixed, thanks.

**Comment by dilyn-corner** [comment]
@aabacchus -- maybe poke `amfora`?

@git-bruh -- maybe poke `github-cli`? 

The others are either wontfix or ignored -- I suppose we should just consider it a lost cause.

Maintainers are probably welcome to vendor dependencies themselves and point `sources` to their fork (though should probably be discussed...)

**Comment by aabacchus** [comment]
Does anyone more familiar with GitHub actions want to have a go at this? https://github.com/makeworld-the-better-one/amfora/issues/296#issuecomment-1140478565

**Comment by aabacchus** [comment]
by the way, the maintainer of aerc said they don't want the "burden" of vendoring deps in tarballs.

**Comment by hovercats** [comment]
I can take `github-cli` and `cloc`.
